server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: sample-java-app
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

logging:
  level:
    com.example: INFO
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 